// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeRxGj_eDO_8lwrMLQqZQESUlEnBqZIs4',
    appId: '1:48821177403:web:2f40b15c5d6cf8d37b201e',
    messagingSenderId: '48821177403',
    projectId: 'salud-4bbb5',
    authDomain: 'salud-4bbb5.firebaseapp.com',
    storageBucket: 'salud-4bbb5.appspot.com',
    measurementId: 'G-4RE9XK0W8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmDBPRP3I6YbaPc0M-ALEAq2iXOFwa43Y',
    appId: '1:48821177403:android:74c6afbf5122a1ca7b201e',
    messagingSenderId: '48821177403',
    projectId: 'salud-4bbb5',
    storageBucket: 'salud-4bbb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAH576I5EgD2lBWVI51MVSP-aiK9enYZA',
    appId: '1:48821177403:ios:6b5d69364139d15b7b201e',
    messagingSenderId: '48821177403',
    projectId: 'salud-4bbb5',
    storageBucket: 'salud-4bbb5.appspot.com',
    iosBundleId: 'com.example.sepconSalud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAH576I5EgD2lBWVI51MVSP-aiK9enYZA',
    appId: '1:48821177403:ios:958b579b19f5e1b07b201e',
    messagingSenderId: '48821177403',
    projectId: 'salud-4bbb5',
    storageBucket: 'salud-4bbb5.appspot.com',
    iosBundleId: 'com.example.sepconSalud.RunnerTests',
  );
}
